# Generated by Django 3.1.6 on 2021-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='lastbody',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='midbody',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
