# Generated by Django 3.1.6 on 2021-06-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_side', '0002_auto_20210619_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
