# Generated by Django 3.1.6 on 2021-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_side', '0004_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, default='/sample.jpeg', null=True, upload_to='')),
            ],
        ),
    ]
