# Generated by Django 3.1.6 on 2021-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
